"use client";

import { useCallback, useEffect, useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { compareActions, getReportPdf, ApiError } from "@/lib/api";
import type { ActionsCompareResponse } from "@/lib/types";
import { formatCount, formatDay, formatInr } from "@/lib/format";
import { EstimateBadge, RiskBadge } from "@/components/ui/badges";
import { ErrorState, LoadingSkeleton } from "@/components/ui/states";

/**
 * Decision report built from live engine output (POST /api/actions/compare)
 * instead of the old hard-coded story, plus a PDF download from
 * GET /api/report. Scenario slider feeds the compare endpoint; default 14
 * days is the demo scenario from the brief.
 */
export default function Report() {
  const [delay, setDelay] = useState(14);
  const [actions, setActions] = useState<ActionsCompareResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<unknown>(null);
  const [pdfState, setPdfState] = useState<"idle" | "busy" | "done" | "fail">("idle");

  const load = useCallback(async (d: number) => {
    setLoading(true);
    setError(null);
    try {
      setActions(await compareActions(d));
    } catch (e) {
      setError(e);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(delay);
  }, [delay, load]);

  const doNothing = actions?.do_nothing;
  const suggested = actions ? Object.values(actions).find((a) => a.suggested) : undefined;

  const downloadPdf = async () => {
    setPdfState("busy");
    try {
      const blob = await getReportPdf();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "bizsim-report.pdf";
      a.click();
      URL.revokeObjectURL(url);
      setPdfState("done");
    } catch {
      setPdfState("fail");
    }
  };

  return (
    <div className="mx-auto max-w-4xl space-y-8">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-3xl font-bold">Decision report</h1>
        <div className="flex items-center gap-3">
          <EstimateBadge />
          <button
            onClick={downloadPdf}
            disabled={pdfState === "busy"}
            className="flex items-center gap-2 rounded-xl bg-primary px-5 py-2.5 text-sm font-medium text-white hover:bg-primary/90 disabled:opacity-50"
          >
            {pdfState === "busy" ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden /> : <Download className="h-4 w-4" aria-hidden />}
            Download PDF
          </button>
        </div>
      </div>
      {pdfState === "fail" && (
        <ErrorState error={new ApiError("The PDF could not be generated.")} title="Download failed" onRetry={downloadPdf} />
      )}
      {pdfState === "done" && (
        <p className="rounded-xl border border-green-500/20 bg-green-500/5 p-3 text-sm text-green-300">
          PDF downloaded — it is generated by the backend (GET /api/report).
        </p>
      )}

      <div className="glass rounded-3xl p-8">
        <div className="border-b border-white/10 pb-6">
          <h2 className="text-2xl font-black">BizSim report</h2>
          <p className="text-sm text-zinc-400">Scenario: Supplier A is {delay} days late (synthetic demo data)</p>
        </div>

        <label htmlFor="report-delay" className="mt-6 mb-1 block text-sm text-zinc-400">
          Delay to report on
        </label>
        <input
          id="report-delay"
          type="range"
          min={0}
          max={30}
          value={delay}
          onChange={(e) => setDelay(Number(e.target.value))}
          className="w-full accent-primary"
        />
        <p className="mb-6 text-right font-mono text-sm text-zinc-300">{delay} days</p>

        {error ? (
          <ErrorState error={error} title="Could not build the report" onRetry={() => load(delay)} />
        ) : loading && !actions ? (
          <LoadingSkeleton rows={4} className="h-20" />
        ) : doNothing && (
          <>
            <div className="space-y-2">
              <h3 className="text-lg font-bold">If nothing is done</h3>
              <ul className="list-disc space-y-1 pl-5 text-sm text-zinc-300">
                <li>Stock runs out on {formatDay(doNothing.summary?.stockout_day)}.</li>
                <li>Cash drops below zero on {formatDay(doNothing.summary?.first_negative_day)} (lowest {formatInr(doNothing.summary?.lowest_cash_inr)}).</li>
                <li>{formatCount(doNothing.summary?.failed_payments_count)} supplier payment(s) fail.</li>
                <li>End cash after 30 days: {formatInr(doNothing.summary?.end_cash_inr)}.</li>
              </ul>
            </div>

            <div className="mt-6 space-y-2">
              <h3 className="text-lg font-bold">What the engine suggests</h3>
              {suggested ? (
                <div className="rounded-xl border border-green-500/30 bg-green-500/5 p-5">
                  <div className="mb-2 flex flex-wrap items-center gap-2">
                    <h4 className="font-bold">{suggested.label}</h4>
                    <RiskBadge level={suggested.risk.level} />
                  </div>
                  <p className="text-sm text-zinc-300">{suggested.suggested_reason}</p>
                  <p className="mt-2 font-mono text-xs text-zinc-400">
                    Lowest cash {formatInr(suggested.summary?.lowest_cash_inr)} · end cash{" "}
                    {formatInr(suggested.summary?.end_cash_inr)} · {formatCount(suggested.summary?.failed_payments_count)}{" "}
                    failed payment(s)
                  </p>
                </div>
              ) : (
                <p className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-5 text-sm text-amber-300">
                  No action avoids the cash gap for this scenario.{" "}
                  {Object.values(actions ?? {})[0]?.suggested_reason}
                </p>
              )}
              <p className="text-xs text-zinc-500">The tool suggests; the owner decides.</p>
            </div>

            <div className="mt-6 space-y-2">
              <h3 className="text-lg font-bold">Assumptions</h3>
              <ul className="list-disc space-y-1 pl-5 text-sm text-zinc-400">
                <li>Demand is held at recent daily averages; a ±band of cases is shown in the Fire Drill.</li>
                <li>No external financing (overdraft, credit line) is modelled.</li>
                <li>All numbers are estimates from a deterministic simulation on synthetic demo data — not predictions.</li>
              </ul>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
